### ISSUE TITLE
codespace creation failure

### ISSUE THREAD

**Issue by djramipro** [alfredodeza/scrapy-xpath#2]
I have encountered a problem when I try to create the codespace in Github. Failed in setup.py but not sure what can change. Could you give me a clue? Many thanks.

Following is part of the creation.log

```
#12 6.436   Preparing metadata (setup.py): started2024-10-06 12:37:37.094Z:
#12 8.992   Preparing metadata (setup.py): finished with status 'error'2024-10-06 12:37:39.650Z:
#12 9.001   error: subprocess-exited-with-error2024-10-06 12:37:39.814Z:
#12 9.001  
#12 9.001   × python setup.py egg_info did not run successfully.2024-10-06 12:37:39.814Z:
#12 9.001   │ exit code: 12024-10-06 12:37:39.814Z:
#12 9.001   ╰─> [37 lines of output]
#12 9.001       WARNING: The wheel package is not available.
#12 9.001       WARNING: The wheel package is not available.
#12 9.001       WARNING: The wheel package is not available.
#12 9.001       Traceback (most recent call last):2024-10-06 12:37:39.815Z:
#12 9.001         File "<string>", line 2, in <module>
#12 9.001         File "<pip-setuptools-caller>", line 34, in <module>
#12 9.001         File "/tmp/pip-install-8du7uqvj/twisted_962f94f13d1f439883aaf00b49091450/setup.py", line 21, in <module>
#12 9.001           setuptools.setup(**_setup["getSetupArgs"]())
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
#12 9.001           return distutils.core.setup(**attrs)
#12 9.001         File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
#12 9.001           _setup_distribution = dist = klass(attrs)2024-10-06 12:37:39.815Z:
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/setuptools/dist.py", line 434, in __init__
#12 9.001           _Distribution.__init__(self, {
#12 9.001         File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
#12 9.001           self.finalize_options()
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/setuptools/dist.py", line 743, in finalize_options
#12 9.001           ep(self)
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/setuptools/dist.py", line 750, in _finalize_setup_keywords
#12 9.001           ep.load()(self, [ep.name](http://ep.name/), value)
#12 9.001         File "/tmp/pip-install-8du7uqvj/twisted_962f94f13d1f439883aaf00b49091450/.eggs/incremental-24.7.2-py3.8.egg/incremental/__init__.py", line 438, in _get_distutils_version
#12 9.001           sp_command.finalize_options()
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/setuptools/command/build_py.py", line 36, in finalize_options
#12 9.001           orig.build_py.finalize_options(self)
#12 9.001         File "/usr/local/lib/python3.8/distutils/command/build_py.py", line 43, in finalize_options
#12 9.001           self.set_undefined_options('build',
#12 9.001         File "/usr/local/lib/python3.8/distutils/cmd.py", line 286, in set_undefined_options
#12 9.001           src_cmd_obj = self.distribution.get_command_obj(src_cmd)
#12 9.001         File "/usr/local/lib/python3.8/distutils/dist.py", line 857, in get_command_obj2024-10-06 12:37:39.816Z:
#12 9.001           klass = self.get_command_class(command)
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/setuptools/dist.py", line 790, in get_command_class
#12 9.001           self.cmdclass[command] = cmdclass = ep.load()
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
#12 9.001           return self.resolve()
#12 9.001         File "/home/vscode/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
#12 9.001           module = __import__(self.module_name, fromlist=['__name__'], level=0)
#12 9.001       ModuleNotFoundError: No module named 'setuptools.command.build'
#12 9.001       [end of output]
#12 9.001  
#12 9.001   note: This error originates from a subprocess, and is likely not a problem with pip.
#12 9.002 error: metadata-generation-failed
#12 9.002
#12 9.002 × Encountered error while generating package metadata.
#12 9.002 ╰─> See above for output.
#12 9.002
#12 9.002 note: This is an issue with the package mentioned above, not pip.
#12 9.002 hint: See above for details.
#12 ERROR: process "/bin/sh -c su vscode -c \"python -m venv /home/vscode/venv\"    && su vscode -c \"${VENV_PATH}/bin/pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt\"    && rm -rf /tmp/pip-tmp" did not complete successfully: exit code: 1
 ------
 > [dev_container_auto_added_stage_label 3/3] RUN su vscode -c "python -m venv /home/vscode/venv"    && su vscode -c "/home/vscode/venv/bin/pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt"    && rm -rf /tmp/pip-tmp:
9.001       [end of output]
9.001  
9.001   note: This error originates from a subprocess, and is likely not a problem with pip.
9.002 error: metadata-generation-failed
9.002
9.002 × Encountered error while generating package metadata.
9.002 ╰─> See above for output.
9.002
9.002 note: This is an issue with the package mentioned above, not pip.
9.002 hint: See above for details.
------

Dockerfile-with-features:13
--------------------
  12 |     COPY requirements.txt /tmp/pip-tmp/
  13 | >>> RUN su vscode -c "python -m venv /home/vscode/venv" \
  14 | >>>    && su vscode -c "${VENV_PATH}/bin/pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt" \
  15 | >>>    && rm -rf /tmp/pip-tmp
  16 |    
--------------------
ERROR: failed to solve: process "/bin/sh -c su vscode -c \"python -m venv /home/vscode/venv\"    && su vscode -c \"${VENV_PATH}/bin/pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt\"    && rm -rf /tmp/pip-tmp" did not complete successfully: exit code: 1
2024-10-06 12:37:40.191Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1728218201889/Dockerfile-with-features -t vsc-scrapy-xpath-3192775456692d9672beebc6f8bda78ba3b216d2de87864f84769c6877520282 --target dev_containers_target_stage --build-arg VARIANT=3.8-bullseye --build-arg NODE_VERSION=none --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.68.0-1728218201889 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/scrapy-xpath
2024-10-06 12:37:40.191Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1728218201889/Dockerfile-with-features -t vsc-scrapy-xpath-3192775456692d9672beebc6f8bda78ba3b216d2de87864f84769c6877520282 --target dev_containers_target_stage --build-arg VARIANT=3.8-bullseye --build-arg NODE_VERSION=none --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.68.0-1728218201889 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/scrapy-xpath
2024-10-06 12:37:40.191Z:     at FtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:466:1933)
2024-10-06 12:37:40.191Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-06 12:37:40.191Z:     at async Pm (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1896)
2024-10-06 12:37:40.191Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1728218201889/Dockerfile-with-features -t vsc-scrapy-xpath-3192775456692d9672beebc6f8bda78ba3b216d2de87864f84769c6877520282 --target dev_containers_target_stage --build-arg VARIANT=3.8-bullseye --build-arg NODE_VERSION=none --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.68.0-1728218201889 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/scrapy-xpath","description":"An error occurred building the image."}
2024-10-06 12:37:40.191Z:     at async NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:610)
2024-10-06 12:37:40.191Z:     at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
2024-10-06 12:37:40.192Z:     at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
2024-10-06 12:37:40.192Z:     at async prA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:663:200)
2024-10-06 12:37:40.192Z:     at async drA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:662:14706)
2024-10-06 12:37:40.197Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2024-10-06 12:37:40.202Z: Failed to create container.
=================================================================================

```

**Comment by alfredodeza** [comment]
@djramipro let me know if that fixes it for you as well. It did for me!
